# Setting
gpus: [0]
seed: 1
debug: False
pretrained_path:
work_dir: ./workdir
no_progress_bar: False


# Data Loader
# ntu, ntu120, ntu_mutual, ntu120_mutual, sbu
dataset: ntu120
dataset_args:
  split: xset
  graph: mutual
  labeling: spatial
  processing: repeat
  train_batch_size: 16
  eval_batch_size: 16
  num_frame: 288
  inputs: joint
  transform: False
  root_folder: ./data/npy_dataset/original
  ntu60_path: /home/m/action_recognition/datasets/ntu60
  ntu120_path: /home/m/action_recognition/datasets/ntu120

# Model
model_type: STGCN
model_args:
  kernel_size: [9,1]

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0001

# Scheduler
# step, cosine
lr_scheduler: step
scheduler_args:
  step:
    max_epoch: 80
    step_lr: [10,50]
    warm_up: 0
  cosine:
    max_epoch: 70
    warm_up: 10