# Setting
gpus: [0]
seed: 1
debug: False
pretrained_path:
work_dir: ./workdir
no_progress_bar: False


# Data Loader
# ntu, ntu120, ntu_mutual, ntu120_mutual, sbu
dataset: sbu
dataset_args:
  fold: 3
  graph: mutual
  labeling: distance
  processing: symmetry
  train_batch_size: 16
  eval_batch_size: 16
  num_frame: 100
  inputs: JVBM
  transform: False
  root_folder: ./data/sbu
  
# Model
# pa, stja, stpa
model_type: 2PGCN
model_args:
  att_type: pa
  kernel_size: [9,2]
  block_structure: b19


# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0002
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0002

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 70
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 50
    warm_up: 5
